/**
 * Internal types for the connections module.
 * Public types live in @kinetiks/types - these are implementation-specific.
 */

import type { ContextLayer, Evidence } from "@kinetiks/types";

/**
 * Decrypted OAuth credentials stored in kinetiks_connections.credentials.
 */
export interface StoredOAuthCredentials {
  type: "oauth";
  access_token: string;
  refresh_token: string | null;
  expires_at: number | null;
  token_type: string;
  scope: string | null;
}

/**
 * Decrypted API key credentials stored in kinetiks_connections.credentials.
 */
export interface StoredApiKeyCredentials {
  type: "api_key";
  api_key: string;
}

export type StoredCredentials = StoredOAuthCredentials | StoredApiKeyCredentials;

/**
 * OAuth endpoint configuration for a provider.
 */
export interface OAuthEndpoints {
  authorizationUrl: string;
  tokenUrl: string;
  scopes: string[];
  clientId: string;
  clientSecret: string;
}

/**
 * Context for an extraction function - everything it needs to pull data and build proposals.
 */
export interface ExtractionContext {
  connectionId: string;
  accountId: string;
  provider: string;
  credentials: StoredCredentials;
  metadata: Record<string, unknown>;
}

/**
 * A proposal generated by a data extraction pass.
 */
export interface ExtractedProposal {
  target_layer: ContextLayer;
  action: "add" | "update";
  confidence: "validated" | "inferred";
  payload: Record<string, unknown>;
  evidence: Evidence[];
}
