export type {
  ContextStructure,
  ContextLayer,
  OrgData,
  ProductsData,
  Product,
  VoiceData,
  VoiceTone,
  CustomersData,
  Persona,
  NarrativeData,
  CompetitiveData,
  Competitor,
  MarketData,
  MarketTrend,
} from "./context";
export type {
  Proposal,
  ProposalAction,
  ProposalConfidence,
  ProposalStatus,
  Evidence,
} from "./proposal";
export type { RoutingEvent } from "./routing";
export type { BrandLayer } from "./brand";
export type {
  MarcusThread,
  MarcusMessage,
  MarcusSchedule,
  MarcusAlert,
  MarcusFollowUp,
  MarcusChannel,
  MarcusIntent,
  MarcusScheduleType,
  MarcusDeliveryChannel,
  MarcusAlertTrigger,
  ExtractedProposal,
  ExtractedBrief,
  ExtractedFollowUp,
  ExtractedAction,
  MarcusChatRequest,
  MarcusChatResponse,
  ContextBudget,
} from "./marcus";
export { CONTEXT_BUDGETS } from "./marcus";
export type {
  ConnectionProvider,
  SystemConnectionProvider,
  AnyConnectionProvider,
  ConnectionStatus,
  ConnectionAuthType,
  ConnectionRecord,
  ConnectionPublic,
  ProviderCategory,
  ProviderDefinition,
  OAuthTokens,
  DataExtractionResult,
  ConnectionSyncLog,
} from "./connections";
export type {
  BillingPlan,
  BillingPlanStatus,
  BillingRecord,
  AppActivationStatus,
  KineticsAppName,
  AppActivation,
  SynapseStatus,
  SynapseRecord,
  ImportType,
  ImportStatus,
  ImportRecord,
  LedgerEventType,
  LedgerEventDetailMap,
  LedgerEntry,
  AuthorityRevocationReason,
  AuthorityEscalationTriggerType,
  AuthorityActionEscalatedDetail,
} from "./billing";
export type {
  ApiResponse,
  ApiSuccessResponse,
  ApiErrorResponse,
  ApiResponseMeta,
  ApiKeyPermission,
  AuthMethod,
  AuthenticatedContext,
  ApiKeyRecord,
  ApiKeyPublic,
  RateLimitResult,
  WebhookEventType,
  WebhookConfig,
  WebhookConfigPublic,
  WebhookDelivery,
  WebhookPayloadEnvelope,
} from "./api";
export type {
  ToolDescriptor,
  ActionClassDescriptor,
  OperatorDescriptor,
  AvailabilityPredicate,
  RateLimitConfig,
  LLMJudgmentModel,
  LLMJudgmentFallback,
  LLMJudgmentBudget,
  PatternTypeDescriptor,
  PatternDecayBounds,
  PatternConfidenceThresholds,
} from "./descriptors";
export type {
  WorkflowTask,
  WorkflowDefinition,
  WorkflowDispatchContext,
  WorkflowTaskResult,
  WorkflowRunSummary,
} from "./workflows";
export type { KineticsAppManifest } from "./manifests";
export type { DefaultStandingGrant } from "./default-grants";
export type {
  SocialPostRecord,
  SocialPostSource,
  SocialEngagementMetrics,
  SocialPostMetadata,
} from "./social";
export type {
  Pattern,
  PatternLifecycleStatus,
  PatternOutcomeDirection,
  PatternEvidenceSummary,
  PatternImportedFrom,
  PatternEmissionPayload,
  PatternEmissionResult,
  PatternExportSchemaVersion,
  PatternExportRequest,
  PatternExportEntry,
  PatternExportPayload,
  PatternTypeDescriptorSnapshot,
  PatternImportResult,
} from "./patterns";
export type {
  AuthorityGrant,
  AuthorityGrantStatus,
  AuthorityGrantScopeType,
  GrantedCapability,
  EscalationTrigger,
  EscalationTriggerType,
  AuthorityUsageSummary,
  GrantProposalEnvelope,
  GrantProposalEnvelopeMember,
  GrantProposalEvidence,
  ProposedGrantBundle,
} from "./authority-grants";
export type {
  ThresholdCondition,
  PacingCondition,
  NoveltyCondition,
  AnomalyCondition,
  LLMJudgedCondition,
} from "./authority-triggers";
export {
  thresholdConditionSchema,
  pacingConditionSchema,
  noveltyConditionSchema,
  anomalyConditionSchema,
  llmJudgedConditionSchema,
  ESCALATION_TRIGGER_CONDITION_SCHEMAS,
  parseEscalationCondition,
} from "./authority-triggers";
export type {
  SentinelVerdict,
  ReviewResolution,
  SentinelContentType,
  FlagCategory,
  FlagSeverity,
  SentinelFlag,
  EditorialScores,
  EditorialResult,
  BrandSafetyCategory,
  BrandSafetyResult,
  ComplianceRule,
  ComplianceCheckResult,
  TouchpointChannel,
  TouchpointSentiment,
  EngagementLevel,
  TouchpointRecord,
  FatigueRuleScope,
  FatigueRule,
  FatigueDecision,
  FatigueCheckResult,
  EscalationSeverity,
  EscalationStatus,
  EscalationDeliveryChannel,
  Escalation,
  OverrideType,
  OverrideUserAction,
  SentinelOverride,
  SentinelReview,
  ReviewRequest,
  ReviewResponse,
} from "./sentinel";
export type {
  KinetiksDesktopBridge,
  DesktopPlatform,
  DesktopNotification,
  DesktopMenuAction,
  DesktopUpdateStatus,
} from "./desktop";
export type {
  CollaborativeParticipant,
  TempoMode,
  PresenceEventType,
  PresenceTarget,
  PresenceMetadata,
  PresenceEvent,
  UIStateChangeType,
  UIStateChange,
  AnnotationKind,
  AnnotationPosition,
  AnnotationAnchor,
  AnnotationReply,
  AnnotationReference,
  Annotation,
  DelegationRegion,
  WorkspaceActionType,
  WorkspaceAction,
  ActiveTaskStatus,
  ActiveTaskStepStatus,
  ActiveTaskStep,
  ActiveTask,
  KillReasonCode,
  KillSignal,
  AppPanelOpen,
  EmbedTarget,
  PanelMessage,
  PanelMessageType,
} from "./collaborative";
// Runtime value (not a type) — the panel-message source tag.
export { PANEL_MESSAGE_SOURCE } from "./collaborative";
